Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -81,7 +81,7 @@ jobs:
           ANDROID_NDK_ROOT: /opt/android-ndk
         run: |
           echo "Downloading Android NDK..."
-          wget --timeout=60 --tries=3 https://dl.google.com/android/repository/android-ndk-r25.1.8937393-linux.zip -O android-ndk.zip || { echo "Download failed"; exit 1; }
+          wget --timeout=60 --tries=3 https://dl.google.com/android/repository/android-ndk-r26b-linux.zip -O android-ndk.zip || { echo "Download failed"; exit 1; }
           echo "Unpacking Android NDK..."
           unzip android-ndk.zip -d $ANDROID_NDK_ROOT || { echo "Unzip failed"; exit 1; }
           echo "Cleaning up..."
